[package]
name = "linkars"
version = "0.0.0"
edition = "2021"

[lib]
name = "linkars"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }
rayon = "*"
flate2 = "*"
sprs = "*"