[package]
name = "linkapy"
version = "1.2.1"
edition = "2021"

[lib]
name = "linkapy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
rayon = "*"
flate2 = "*"
sprs = "*"